### ISSUE TITLE
Non-existent student leftover in class

### ISSUE THREAD

**Issue by adam-ky** [AY2122S1-CS2103T-T12-4/tp#173]
Attempt to `deleteclass 1` results in an unhandled error.

Not very useful as I don't remember how to reproduce this bug (was done a while back). 

![image](https://user-images.githubusercontent.com/69505439/139521084-3a6a541c-ef9f-43d3-8d7d-87dbafcd5ce7.png)

**Comment by amzhy** [comment]
Yes it's because `rec` command changes the internal id for the class, so the class id in the student is different from the class id, causing `del` and `delc` to fail. Related issue: #167
